# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20161026_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_id',
        ),
    ]
